/**
 * AnalogDesk - replay cache.
 *
 * A live model call costs latency, money and network reachability, none of which a judge reviewing
 * a static deployment has. So every successful generation is stored against a digest of the exact
 * card + prompt version + language that produced it, and can be replayed verbatim later. Replayed
 * text still goes through the numeric gate: a cache is not a licence to skip verification.
 *
 * Two stores, same interface:
 *   NodeStore    - JSON files under data-cache/llm-replay, used by server.mjs and the CLI
 *   MemoryStore  - a plain object, used by the browser bundle (seeded at build time)
 *
 * THE DIGEST IS A CONTRACT, NOT AN IMPLEMENTATION DETAIL.
 * A record warmed on one runtime is only useful if a different runtime asking the same research
 * question hashes to the same id. Three things used to break that, and each one made REPLAY
 * unreachable rather than merely stale:
 *
 *   1. buildCard() stamps `generatedAt` with the current time, so two identical requests hashed
 *      differently and no cached record could ever be found again.
 *   2. The browser runtime REWRITES card.provenance before narrating (it injects the baked bitget
 *      probe block and llm.mode/keyPresent), while server.mjs injects a live probe result. The same
 *      research question therefore hashed to different ids in the static bundle and on the server,
 *      so anything warmed with an API key was invisible to the judge who has none.
 *   3. The model name was mixed into the key, but the static bundle cannot know it and passes "".
 *      A qwen-plus record was filed under an id the browser would never compute.
 *
 * So the digest is taken over `stableCardView(card)`: the card with every environment-, clock- and
 * machine-dependent field removed. What is left is exactly the research question and the numbers
 * the engine measured for it - which is what a cached narrative is actually a claim about.
 * `scripts/check-replay.mjs` asserts these invariants so the bug class cannot return silently.
 */

/**
 * Card fields describing WHEN, WHERE or HOW FAST an answer was produced rather than WHAT was asked
 * and WHAT the engine measured. Exported so a gate can assert the list has not quietly grown: every
 * addition widens cache sharing, and a widening nobody reviewed is how stale prose reaches a judge.
 */
export const DIGEST_VOLATILE_KEYS = Object.freeze([
  // clocks
  "generatedAt", "storedAt", "probedAt", "checkedAt", "builtAt", "datasetBuiltAt",
  // environment / venue reachability (reviewer-dependent, and rewritten per runtime)
  "provenance", "networkProbe", "bitget", "llm",
  // machine-speed measurements; research/validation-results.json is regenerated by `npm run verify`
  "timing", "meanRetrievalMs", "meanQueryMs", "queryMs", "initMs", "wallMs",
  "latencyMs", "retrievalMs", "engineInitMs"
]);

const VOLATILE = new Set(DIGEST_VOLATILE_KEYS);

/**
 * Deep copy of `card` with every volatile key removed and object keys sorted at every level, so the
 * hash depends on the card's CONTENT and not on the order fields happened to be assigned in.
 * Arrays keep their order: an analog list in a different order is a different retrieval.
 */
export function stableCardView(card) {
  const walk = (node) => {
    if (Array.isArray(node)) return node.map(walk);
    if (node && typeof node === "object") {
      const out = {};
      for (const k of Object.keys(node).sort()) {
        if (VOLATILE.has(k)) continue;
        const v = walk(node[k]);
        if (v !== undefined) out[k] = v;
      }
      return out;
    }
    return node;
  };
  return walk(card);
}

/**
 * Stable id for "this research question, at these engine settings, with these measured numbers,
 * answered in this language, by this prompt version".
 *
 * `language` IS part of the identity: the card does not change between a Chinese and an English
 * question, but the prose does, and one slot holding both would serve a judge Chinese text for an
 * English question. `model` is deliberately NOT part of it - the static bundle cannot know which
 * model wrote a record, and which model produced the prose is metadata stored inside the record and
 * shown on the card badge, not part of the question being asked.
 */
export function cardDigest(card, { promptVersion = "1", language = "" } = {}) {
  const canon = JSON.stringify(stableCardView(card));
  const key = `${promptVersion}|${String(language || "").toLowerCase()}|${canon}`;
  // FNV-1a 32-bit over the canonical string, then mixed with a length term. Deterministic, no deps.
  let h = 0x811c9dc5;
  for (let i = 0; i < key.length; i++) { h ^= key.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  h = (h ^ Math.imul(key.length, 2654435761)) >>> 0;
  return h.toString(16).padStart(8, "0");
}

export class MemoryStore {
  constructor(seed = {}) { this.map = new Map(Object.entries(seed || {})); }
  async get(id) { return this.map.get(id) || null; }
  async set(id, rec) { this.map.set(id, rec); return id; }
  async list() { return [...this.map.keys()]; }
}

export function createNodeStore(dir) {
  const { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } = require_fs();
  if (dir && !existsSync(dir)) mkdirSync(dir, { recursive: true });
  const path = (id) => `${dir.replace(/[\\/]+$/, "")}/${id}.json`;
  return {
    dir,
    async get(id) {
      try { return JSON.parse(readFileSync(path(id), "utf8")); } catch { return null; }
    },
    async set(id, rec) {
      try { writeFileSync(path(id), JSON.stringify(rec, null, 2), "utf8"); } catch { /* read-only fs: replay simply won't persist */ }
      return id;
    },
    async list() {
      try { return readdirSync(dir).filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")); } catch { return []; }
    }
  };
}

let _fs = null;
function require_fs() {
  if (_fs) return _fs;
  // Lazy, guarded: keeps this module importable in a browser bundle where node:fs does not exist.
  try {
    // eslint-disable-next-line no-undef
    _fs = globalThis.__analogdeskFs || null;
  } catch { _fs = null; }
  if (!_fs) throw new Error("node fs not registered - call registerNodeFs() or use MemoryStore");
  return _fs;
}

/** server.mjs calls this once at startup so this module stays browser-safe. */
export function registerNodeFs(fsModule) { _fs = fsModule; }
