/**
 * AnalogDesk - complete research task runner.
 *
 *   npm run demo                 runs the default task and writes demo/
 *   node scripts/run-demo.mjs --symbol BABA --horizon 5 --question "..."
 *
 * Track 3 (AI Trading Desk) requires ONE complete research task: question -> actionable insight,
 * and the submission rules require the report to ship with the code that generated it rather than
 * as screenshots. This script is that code. It runs the real engine - the same createDesk() that
 * server.mjs and the static bundle use - and writes:
 *
 *   demo/run-record.json   the full machine-readable record: the question, the frozen engine
 *                          config, the complete research card, the narrative with its numeric-gate
 *                          result, every stress scenario, and the out-of-sample validation
 *   demo/RUN-RECORD.md     the human-readable version of the same run, for the form and the video
 *
 * Nothing in either file is hand-written. Every figure comes from the engine payload, and the
 * narrative is re-checked by src/llm/verify-numbers.mjs before it is written; if the gate rejects
 * it, the run fails loudly instead of publishing prose containing an unsupported number.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { resolveConfig } from "../src/llm/config.mjs";
import { registerNodeFs, createNodeStore } from "../src/llm/replay.mjs";
import { narrate, detectLang, PROMPT_VERSION } from "../src/llm/narrate.mjs";
import { probeAllBitget } from "../src/data/bitget.mjs";
import { buildAllowlist, verifyNumbers, defaultAllowance } from "../src/llm/verify-numbers.mjs";
import { createDesk, DEFAULT_HORIZON, DEFAULT_K } from "../src/desk.mjs";
import * as fs from "node:fs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const OUT = join(ROOT, "demo");
const log = (...a) => console.log("[demo]", ...a);
const readJson = (p) => { try { return JSON.parse(readFileSync(p, "utf8")); } catch { return null; } };

/* ------------------------------- arguments ------------------------------- */

const DEFAULT_QUESTION =
  "NVDA is at its 52-week-high area after a strong run. Before I open a position, what did the " +
  "historical episodes that most resemble this state actually do over the next trading week, and " +
  "how bad does the path get in the scenarios I should be worried about?";

function parseArgs(argv) {
  const a = { symbol: "NVDA", horizon: DEFAULT_HORIZON, k: DEFAULT_K, date: "latest", question: DEFAULT_QUESTION, language: null, stress: true };
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i], v = argv[i + 1];
    if (k === "--symbol" || k === "-s") { a.symbol = String(v).toUpperCase(); i++; }
    else if (k === "--horizon" || k === "-H") { a.horizon = Number(v); i++; }
    else if (k === "--k" || k === "-k") { a.k = Number(v); i++; }
    else if (k === "--date" || k === "-d") { a.date = String(v); i++; }
    else if (k === "--question" || k === "-q") { a.question = String(v); i++; }
    else if (k === "--language" || k === "-l") { a.language = String(v); i++; }
    else if (k === "--no-stress") { a.stress = false; }
    else if (k === "--help" || k === "-h") { log("usage: node scripts/run-demo.mjs [--symbol NVDA] [--horizon 5] [--k 50] [--date latest] [--question \"...\"] [--language en|zh] [--no-stress]"); process.exit(0); }
  }
  return a;
}

/* ------------------------------ markdown -------------------------------- */

const mdEsc = (s) => String(s ?? "").replace(/\|/g, "\\|");
const n = (x, dp = 2) => (x == null || !Number.isFinite(Number(x)) ? "\u2013" : Number(x).toFixed(dp));
const p = (x, dp = 2) => (x == null || !Number.isFinite(Number(x)) ? "\u2013" : `${Number(x) > 0 ? "+" : ""}${Number(x).toFixed(dp)}%`);
const pl = (x, dp = 1) => (x == null || !Number.isFinite(Number(x)) ? "\u2013" : `${Number(x).toFixed(dp)}%`);

function renderMarkdown(ctx) {
  const { args, card, narrative, gate, validation, bitget, bitgetProbeSource, timing, cfg, prov, task } = ctx;
  const i = card.idea, r = card.retrieval, d = card.distribution, e = card.excursion, c = card.conformal;
  const L = [];
  L.push(`# AnalogDesk - complete research task run record`);
  L.push(``);
  L.push(`Generated by \`node scripts/run-demo.mjs\` at **${ctx.startedAt}**. This file is produced by code,`);
  L.push(`not written by hand and not a screenshot: the script that generated it is in this repository, and the`);
  L.push(`machine-readable record with every underlying figure is \`demo/run-record.json\`.`);
  L.push(``);
  L.push(`| | |`);
  L.push(`|---|---|`);
  L.push(`| Track | Bitget Hackathon S2 - Track 3 AI Trading Desk - sub-theme **Decision Stress Testing** |`);
  L.push(`| Question asked | ${mdEsc(args.question)} |`);
  L.push(`| Instrument | ${mdEsc(i.name)} (${mdEsc(i.symbol)}), ${mdEsc(i.sector || "n/a")} |`);
  L.push(`| Decision session | ${mdEsc(i.asOfSession)}, adjusted close ${n(i.referenceClose, 4)} (return basis), raw close ${n(i.referenceCloseRaw, 4)} (path-risk basis) |`);
  L.push(`| Horizon | ${mdEsc(i.horizonLabel)} |`);
  L.push(`| Narrative mode | **${narrative.mode}**${narrative.model ? ` (${narrative.model})` : ""} |`);
  L.push(`| Numeric gate | ${gate.ok ? "**PASS**" : "**FAIL**"} - ${gate.total - gate.unsupportedCount}/${gate.total} numerals traced to the research card |`);
  L.push(`| Wall time | engine init ${n(timing.engineInitMs, 0)} ms, analysis ${n(timing.analyzeMs, 0)} ms (retrieval ${n(timing.retrievalMs, 0)} ms), narrative ${isFinite(narrative.latencyMs) ? n(narrative.latencyMs, 0) + " ms" : "n/a (no model call)"} |`);
  L.push(``);
  L.push(`---`);
  L.push(``);
  L.push(`## 1. The task`);
  L.push(``);
  L.push(task);
  L.push(``);
  L.push(`## 2. What the engine was told to do`);
  L.push(``);
  L.push(`Frozen configuration. Nothing here is fitted at request time - a live query may not re-calibrate`);
  L.push(`on the very data the trader is asking about.`);
  L.push(``);
  L.push(`| Setting | Value |`);
  L.push(`|---|---|`);
  L.push(`| Analog library | ${n(prov.sessions, 0)} sessions x ${n(prov.symbols, 0)} instruments, ${mdEsc(prov.from)} .. ${mdEsc(prov.to)} |`);
  L.push(`| Neighbours retrieved | k = ${n(r.kRequested, 0)} requested, ${n(r.kReturned, 0)} returned |`);
  L.push(`| Features carried | ${n(prov.nFeatures, 0)} in ${card.currentState?.groups?.length ?? 0} groups |`);
  L.push(`| Features in the distance metric | ${n(prov.metricFeatures, 0)} |`);
  L.push(`| Excluded from the metric | \`${mdEsc((prov.excludedFromDistance || []).join(", "))}\` - carried and displayed, never scored |`);
  L.push(`| Group weights | ${mdEsc((card.currentState?.groups || []).map((g) => `${g.group} ${g.weightPct}%`).join(", "))} |`);
  L.push(`| Standardisation | expanding point-in-time z-score, winsorised at +/-${n(prov.zClip, 0)} sigma |`);
  L.push(`| Anti-clustering | <= ${n(prov.maxPerCalendarDate, 0)} analogs per calendar date; same instrument >= ${n(prov.minSameSymbolGap, 0)} sessions apart |`);
  L.push(`| Leakage embargo | candidate session j eligible only if j + ${n(r.embargoSessions, 0)} <= query session |`);
  L.push(`| Return basis | adjusted close, A[q+H]/A[q] - 1 |`);
  L.push(`| Path-risk basis | raw session OHLC: MAE/MFE are the raw low/high over the horizon against the raw close of the decision session; gap20 is raw open[t] / raw close[t-1] - 1. No raw price is ever divided by an adjusted one |`);
  L.push(`| Conformal scale | ${n(c?.scale, 3)}, fitted on ${mdEsc(c?.fittedOn || "n/a")} and frozen |`);
  L.push(``);
  L.push(`## 3. Result - the distribution of what actually happened next`);
  L.push(``);
  if (!d) { L.push(`The engine returned no usable analog sample for this query.`); }
  else {
    L.push(`Over the ${mdEsc(i.horizonLabel)} following ${n(d.n, 0)} retrieved historical episodes:`);
    L.push(``);
    L.push(`| Statistic | Value |`);
    L.push(`|---|---|`);
    L.push(`| Median forward return | ${p(d.medianPct)} |`);
    L.push(`| Mean forward return | ${p(d.meanPct)} |`);
    L.push(`| Standard deviation | ${pl(d.sdPct)} |`);
    L.push(`| Middle 80% (p10 - p90) | ${p(d.p10Pct)} to ${p(d.p90Pct)} |`);
    L.push(`| Middle 50% (p25 - p75) | ${p(d.p25Pct)} to ${p(d.p75Pct)} |`);
    L.push(`| Full range | ${p(d.minPct)} to ${p(d.maxPct)} |`);
    L.push(`| Skew | ${n(d.skew, 2)} |`);
    L.push(`| Share closing below the entry | ${pl(d.probabilityBelowZeroPct)} |`);
    L.push(`| P(loss > 5% / 10% / 20%) | ${pl(d.probabilityBelow?.minus5Pct)} / ${pl(d.probabilityBelow?.minus10Pct)} / ${pl(d.probabilityBelow?.minus20Pct)} |`);
    L.push(`| VaR90 / CVaR90 | ${n(d.valueAtRisk90Pct)}% / ${n(d.conditionalVar90Pct)}% |`);
    L.push(``);
    if (c) {
      L.push(`**Conformal interval.** Rescaled to its ${pl(c.coverageTargetPct, 0)} coverage target by the frozen multiplier`);
      L.push(`${n(c.scale, 3)}, the interval is **${p(c.lowerPct)} to ${p(c.upperPct)}**, ${pl(c.widthPct)} wide. Measured strictly out of`);
      L.push(`sample on ${mdEsc(c.testEra || "the test era")}, this construction covered the realised outcome ${pl(c.outOfSampleCoveragePct)}`);
      L.push(`of the time (+/- ${n(c.outOfSampleSEPp, 2)} pp clustered SE) over ${n(c.testQueries, 0)} queries.`);
      L.push(``);
    }
    if (e) {
      L.push(`**Path risk, not just the endpoint.** A trade can finish near flat and still have been un-holdable.`);
      L.push(``);
      L.push(`| Statistic | Value |`);
      L.push(`|---|---|`);
      L.push(`| Median max adverse excursion | ${p(e.maxAdverseMedianPct)} |`);
      L.push(`| MAE p10 (worst tenth) | ${p(e.maxAdverseP10Pct)} |`);
      L.push(`| Median max favourable excursion | ${p(e.maxFavourableMedianPct)} |`);
      L.push(`| Reward / risk (MFE med : abs MAE med) | ${n(e.rewardRiskRatio, 2)} |`);
      for (const [k, v] of Object.entries(e.probabilityOfBreaching || {})) {
        L.push(`| P(breaching ${mdEsc(String(k).replace("PctDrawdown", ""))}% drawdown intra-path) | ${pl(v)} |`);
      }
      L.push(``);
    }
  }
  return L.join("\n");
}

function renderMarkdownPart2(ctx) {
  const { card, narrative, gate, validation, bitget, bitgetProbeSource, prov, cfg, args } = ctx;
  const L = [];
  const st = card.stress || [];
  L.push(`## 4. Decision stress testing`);
  L.push(``);
  if (!st.length) {
    L.push(`The stress suite was not run for this invocation (\`--no-stress\`).`);
  } else {
    L.push(`Every scenario re-runs the SAME engine with the SAME settings, so each row is directly comparable to`);
    L.push(`the baseline. **Window** scenarios pin the analog library to a named historical episode; **shock** scenarios`);
    L.push(`move the query state in z-space and re-retrieve across the whole library.`);
    L.push(``);
    L.push(`| Scenario | Kind | Analogs | Median fwd | Delta vs base | p10 | p90 | P(loss>10%) | Median MAE | P(10% dd) | Held within 10% dd |`);
    L.push(`|---|---|---|---|---|---|---|---|---|---|---|`);
    for (const s of st) {
      if (s.skipped) { L.push(`| ${mdEsc(s.label)} | ${mdEsc(s.kind)} | \u2013 | _skipped: ${mdEsc(s.skipped)}_ | | | | | | | |`); continue; }
      L.push(`| ${mdEsc(s.label)} | ${mdEsc(s.kind)} | ${n(s.analogsUsed, 0)} | ${p(s.medianForwardPct)} | ${s.deltaMedianVsBaselinePct == null ? "\u2013" : p(s.deltaMedianVsBaselinePct)} | ${p(s.p10ForwardPct)} | ${p(s.p90ForwardPct)} | ${pl(s.probabilityBelowMinus10Pct)} | ${p(s.maxAdverseMedianPct)} | ${pl(s.probabilityOfBreaching10PctDrawdown)} | ${pl(s.heldWithin10PctDrawdown)} |`);
    }
    L.push(``);
    const worst = st.filter((s) => !s.skipped && s.id !== "baseline" && s.deltaMedianVsBaselinePct != null)
      .sort((a, b) => a.deltaMedianVsBaselinePct - b.deltaMedianVsBaselinePct).slice(0, 3);
    if (worst.length) {
      L.push(`**The three scenarios that most worsen the picture**, each with the engine's own caveat carried verbatim:`);
      L.push(``);
      for (const w of worst) {
        L.push(`- **${mdEsc(w.label)}** - median ${p(w.medianForwardPct)} (${p(w.deltaMedianVsBaselinePct)} vs baseline), P(loss > 10%) ${pl(w.probabilityBelowMinus10Pct)}, median MAE ${p(w.maxAdverseMedianPct)}.`);
        L.push(`  - Why it is in the suite: ${mdEsc(w.why)}`);
        L.push(`  - Caveat: ${mdEsc(w.caveat)}`);
      }
      L.push(``);
    }
    const skipped = st.filter((s) => s.skipped);
    if (skipped.length) {
      L.push(`**Skipped, disclosed rather than hidden:** ${mdEsc(skipped.map((s) => `${s.label} (${s.skipped})`).join("; "))}.`);
      L.push(`A scenario suite that conceals its own gaps is worse than no suite at all.`);
      L.push(``);
    }
  }

  L.push(`## 5. Which historical episodes were retrieved`);
  L.push(``);
  const r = card.retrieval || {};
  L.push(`${n(r.kReturned, 0)} analogs across ${n(r.distinctSessions, 0)} distinct sessions and ${n(r.distinctSymbols, 0)} distinct instruments,`);
  L.push(`of which ${n(r.sameSymbolCount, 0)} are ${mdEsc(card.idea.symbol)} itself. Closest distance ${n(r.closestDistance, 4)},`);
  L.push(`median distance ${n(r.medianDistance, 4)} in group-weighted z-space. Span ${mdEsc(r.analogDateFrom)} .. ${mdEsc(r.analogDateTo)}.`);
  L.push(``);
  L.push(`Concentration by sector: ${mdEsc(Object.entries(r.bySector || {}).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(", ") || "n/a")}.`);
  L.push(``);
  L.push(`Concentration by year: ${mdEsc(Object.entries(r.byYear || {}).sort((a, b) => a[0].localeCompare(b[0])).map(([k, v]) => `${k} ${v}`).join(", ") || "n/a")}.`);
  L.push(``);
  L.push(`The twelve closest matches:`);
  L.push(``);
  L.push(`| # | Symbol | Session | Sector | Distance | Forward return | MAE | MFE |`);
  L.push(`|---|---|---|---|---|---|---|---|`);
  (r.top || []).forEach((a, idx) => {
    L.push(`| ${idx + 1} | ${mdEsc(a.symbol)}${a.symbol === card.idea.symbol ? " (same name)" : ""} | ${mdEsc(a.session)} | ${mdEsc(a.sector || "\u2013")} | ${n(a.distance, 4)} | ${p(a.forwardReturnPct)} | ${p(a.maxAdverseExcursionPct)} | ${p(a.maxFavourableExcursionPct)} |`);
  });
  L.push(``);
  L.push(`The full ${n(r.kReturned, 0)}-row list is in \`demo/run-record.json\` under \`detail.analogs\`.`);
  L.push(``);

  L.push(`## 6. Narrative layer`);
  L.push(``);
  L.push(`Mode **${narrative.mode}**${narrative.model ? `, model \`${narrative.model}\`` : ""}, prompt version ${ctx.promptVersion}.`);
  L.push(`The model sees the research card and nothing else. Every numeral it writes is checked against that card`);
  L.push(`by \`src/llm/verify-numbers.mjs\`; a draft citing an unsupported figure is rejected after one corrective`);
  L.push(`retry and the deterministic template is shown instead. **Numeric gate: ${gate.ok ? "PASS" : "FAIL"}** -`);
  L.push(`${gate.total - gate.unsupportedCount}/${gate.total} numerals traced to the card.`);
  L.push(``);
  if (narrative.warnings?.length) {
    L.push(`Warnings recorded by the pipeline:`);
    for (const w of narrative.warnings) L.push(`- ${mdEsc(w)}`);
    L.push(``);
  }
  for (const k of narrative.order || Object.keys(narrative.sections || {})) {
    const body = narrative.sections?.[k];
    if (!body) continue;
    L.push(`### [${k}]`);
    L.push(``);
    L.push(body);
    L.push(``);
  }

  L.push(`## 7. Out-of-sample validation of the engine itself`);
  L.push(``);
  if (!validation) {
    L.push(`No frozen validation summary is loaded for this horizon. Run \`npm run verify\`.`);
  } else {
    L.push(`Pre-registered protocol: ${mdEsc(validation.protocol)}. Target coverage ${pl(validation.targetCoveragePct, 0)}.`);
    L.push(``);
    L.push(`| Predictive band | Coverage (test era) | Mean width | Width at matched coverage |`);
    L.push(`|---|---|---|---|`);
    L.push(`| **Analog + frozen conformal scale (this project)** | **${pl(validation.analog.coveragePct)}** (+/- ${n(validation.analog.coverageSEPp, 2)} pp) | ${pl(validation.analog.widthPct)} | ${pl(validation.analog.matchedCoverageWidthPct)} |`);
    for (const [k, label] of [["analogRaw", "Analog raw percentiles, uncalibrated"], ["uncondNamePIT", "Same-name unconditional, point-in-time"], ["volHarness", "Own-volatility harness"], ["pooledUncond", "Pooled unconditional, whole library"]]) {
      const b = validation.benchmarks?.[k];
      if (b) L.push(`| ${label} | ${pl(b.coveragePct)} | ${pl(b.widthPct)} | ${pl(b.matchedCoverageWidthPct)} |`);
    }
    L.push(``);
    L.push(`| Diagnostic | Value |`);
    L.push(`|---|---|`);
    L.push(`| Sharpness vs the same-name band at matched coverage | ${p(validation.matchedCoverageSharpnessVsSameNamePct)} (negative = the analog band is **wider**) |`);
    L.push(`| Per-symbol coverage sd | analog ${n(validation.perSymbolCoverageSdPp?.analogConformal, 1)} pp, same-name ${n(validation.perSymbolCoverageSdPp?.uncondNamePIT, 1)} pp, pooled ${n(validation.perSymbolCoverageSdPp?.pooledUncond, 1)} pp |`);
    L.push(`| PIT uniformity chi-square | ${n(validation.pitChiSquare, 1)} vs 5% critical ${n(validation.pitChiSquareCritical5Pct, 1)} - ${validation.pitChiSquare > validation.pitChiSquareCritical5Pct ? "**FAILS**" : "passes"} |`);
    L.push(`| Directional hit rate of the analog median | ${pl(validation.directionalHitRatePct)} |`);
    L.push(`| Mean retrieval time | ${n(validation.meanRetrievalMs, 1)} ms |`);
    L.push(``);
    L.push(`> ${mdEsc(validation.honestVerdict || "")}`);
    L.push(``);
    L.push(`Full detail, per horizon and per symbol: \`research/VALIDATION.md\` and \`research/validation-results.json\`.`);
  }
  L.push(``);

  L.push(`## 8. Data provenance and network reachability, as measured`);
  L.push(``);
  L.push(`| Source | Endpoint |`);
  L.push(`|---|---|`);
  for (const [k, v] of Object.entries(prov.sources || {})) L.push(`| ${mdEsc(k)} | ${mdEsc(typeof v === "string" ? v : JSON.stringify(v))} |`);
  L.push(``);
  L.push(`Dataset built ${mdEsc(prov.datasetBuiltAt || "n/a")}. Library ${mdEsc(prov.from)} .. ${mdEsc(prov.to)}, ${n(prov.sessions, 0)} sessions, ${n(prov.symbols, 0)} instruments.`);
  L.push(`Two price bases are carried per symbol and never mixed: every forward return uses the adjusted close (split + dividend), while path risk (MAE/MFE) and the gap20 feature use raw session OHLC - the raw low/high against the raw close of the decision session, and the raw open against the previous raw close. The vendor supplies both bases on one row; a row missing either is dropped at fetch time.`);
  L.push(``);
  const np = prov.networkProbe;
  if (np) {
    L.push(`Reachability measured on the build machine at ${mdEsc(np.generatedAt)} by \`scripts/probe-network.mjs\`: ${mdEsc(np.summary)}`);
    L.push(``);
    L.push(`| Host | Status | Reachable | Role |`);
    L.push(`|---|---|---|---|`);
    for (const t of np.targets || []) L.push(`| \`${mdEsc(t.name)}\` | ${t.status ?? "\u2013"} | ${t.ok ? "yes" : `no (${mdEsc(t.kind)})`} | ${mdEsc(t.role)} |`);
    L.push(``);
  }
  L.push(`### Bitget official MCP`);
  L.push(``);
  if (bitget) {
    L.push(`${mdEsc(bitget.summary || "")} (${mdEsc(bitget.probedAt || "n/a")}).`);

    if (bitgetProbeSource) L.push(`Evidence for this probe: ${mdEsc(bitgetProbeSource)}.`);
    for (const e of bitget.endpoints || []) L.push(`- ${e.ok ? "reachable" : "UNREACHABLE"} - ${mdEsc(e.name)} \`${mdEsc(e.url)}\` - ${mdEsc(e.kind || "")}${e.detail ? ": " + mdEsc(e.detail) : ""}`);
    L.push(``);
    if (bitget.disclosure) L.push(`> ${mdEsc(bitget.disclosure)}`);
  } else {
    L.push(`Not probed for this run.`);
  }
  L.push(``);
  L.push(`## 9. Reproducing this run`);
  L.push(``);
  L.push("```bash");
  L.push(`npm install            # zero runtime dependencies; this is a no-op but keeps the flow standard`);
  L.push(`npm run build:data     # rebuild data-cache/dataset.json from the keyless sources (cached; ~10s warm)`);
  L.push(`npm run verify         # re-fit and re-score the frozen validation -> research/VALIDATION.md`);
  L.push(`npm run demo           # regenerate this file and demo/run-record.json`);
  L.push(`npm run check          # numeric-gate grid + static bundle build + in-browser engine check`);
  L.push(`npm start              # the interactive desk at http://127.0.0.1:3000`);
  L.push("```");
  L.push(``);
  L.push(`Exact invocation for this record:`);
  L.push(``);
  L.push("```bash");
  L.push(`node scripts/run-demo.mjs --symbol ${args.symbol} --horizon ${args.horizon} --k ${args.k} --date ${args.date}${args.stress ? "" : " --no-stress"}`);
  L.push("```");
  L.push(``);
  L.push(`Narrative configuration for this run: mode \`${cfg.llm.enabled ? "LIVE" : "TEMPLATE/REPLAY"}\`, model \`${mdEsc(cfg.llm.model)}\`,`);
  L.push(`endpoint \`${mdEsc(cfg.llm.baseUrl)}\`, API key ${cfg.llm.enabled ? "present" : "**not set**"}. With no key the run still completes: every figure above is engine-computed and the narrative comes from the deterministic template, through the same numeric gate.`);
  L.push(`Prompt version ${ctx.promptVersion}.`);
  L.push(``);
  L.push(`---`);
  L.push(``);
  L.push(`**This is research tooling, not investment advice, and not a prediction.** It describes what happened next`);
  L.push(`in historical episodes whose market state resembles the one being queried. See \`research/THESIS.md\`,`);
  L.push(`\`research/VALIDATION.md\`, \`research/DATA-PROVENANCE.md\` and \`research/LIMITATIONS.md\`.`);
  L.push(``);
  return L.join("\n");
}

/* ---------------------------------- main --------------------------------- */

const TASK_NARRATIVE = [
  `A trader is considering opening a position and wants to know, before committing capital, what the`,
  `historical record says about the state they are buying into. The task is deliberately the one the`,
  `sub-theme names - **decision stress testing** - and it has a fixed shape:`,
  ``,
  `1. **Question in plain language.** A natural-language sentence, optionally in Chinese, naming an`,
  `   instrument and a holding period. No query DSL, no parameter form to learn.`,
  `2. **State description.** The engine computes 28 features for the decision session - the instrument's`,
  `   own tape, the benchmark, the rates and inflation complex, the crypto complex (because the`,
  `   reference market for a tokenized stock is a crypto venue), and the scheduled-event calendar - and`,
  `   standardises each on an expanding point-in-time window, so a z-score means the same thing in 2017`,
  `   and in 2026 and nothing downstream can see the future.`,
  `3. **Retrieval.** The 25 metric features are used to find the k nearest (symbol, session) pairs in a`,
  `   decade-long library, under an embargo that guarantees every reported outcome was fully realised`,
  `   before the decision date, plus two anti-clustering constraints so the "distribution" cannot`,
  `   collapse into one week of one crisis.`,
  `4. **Outcome distribution.** What those episodes actually did next: quantiles, tail probabilities,`,
  `   and the intra-path excursion, because an episode that finishes flat after a 20% drawdown was not`,
  `   a holdable trade.`,
  `5. **Calibration.** Raw analog percentiles are systematically over-confident, so a single global`,
  `   multiplier is fitted by split conformal prediction on 2019-2022, frozen, and never re-fitted on`,
  `   anything the trader is asking about.`,
  `6. **Stress suite.** The same engine, the same settings, re-run against named historical windows and`,
  `   against counterfactual shocks applied in z-space - each row carrying its own caveat.`,
  `7. **Actionable insight, and its limits.** A narrative that states what to anchor on, what could make`,
  `   the position un-holdable, and what the analysis cannot tell the trader - including where the`,
  `   engine's own validation shows it does not beat a naive benchmark.`,
  ``,
  `The output is a decision input, not a decision. Nothing here sizes a position or recommends a side.`
].join("\n");

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const startedAt = new Date().toISOString();
  const cfg = resolveConfig();
  registerNodeFs(fs);
  const store = createNodeStore(join(ROOT, "data-cache", "llm-replay"));

  const datasetPath = join(ROOT, "data-cache", "dataset.json");
  if (!existsSync(datasetPath)) { console.error("[demo] data-cache/dataset.json is missing. Run: npm run build:data"); process.exit(1); }
  const dataset = readJson(datasetPath);
  const validationResults = readJson(join(ROOT, "research", "validation-results.json"));
  const networkProbe = readJson(join(ROOT, "data-cache", "network-probe.json"));

  log(`loading analog library ...`);
  const t0 = Date.now();
  const provenanceBase = {
    datasetBuiltAt: dataset.meta?.builtAt || null,
    sources: dataset.meta?.sources || {},
    notes: dataset.meta?.notes || [],
    networkProbe: networkProbe ? {
      generatedAt: networkProbe.generatedAt, summary: networkProbe.summary, host: networkProbe.host, node: networkProbe.node,
      usedSources: networkProbe.usedSources, unusedSources: networkProbe.unusedSources, rejectedSources: networkProbe.rejectedSources,
      targets: (networkProbe.targets || []).map((x) => ({ name: x.name, role: x.role, ok: x.ok, status: x.status, kind: x.kind, detail: x.detail, latencyMs: x.latencyMs }))
    } : null,
    validationGeneratedAt: validationResults?.generatedAt || null
  };
  const desk = createDesk({ dataset, validationResults, provenance: provenanceBase, config: cfg });
  const engineInitMs = Date.now() - t0;
  log(`engine ready in ${engineInitMs} ms - ${desk.engine.mx.nSym} instruments x ${desk.engine.mx.nDates} sessions (${dataset.meta?.from} .. ${dataset.meta?.to})`);

  const persistedBitget = networkProbe?.bitget || null;
  // A probe is only usable as evidence if undici surfaced a transport-level cause. Inside a
  // network sandbox the live probe can only report a generic "fetch failed", which says nothing
  // about WHY Bitget is unreachable, so the earlier escalated probe is kept and labelled.
  const isClassified = (p) => Array.isArray(p?.endpoints) && p.endpoints.length > 0
    && p.endpoints.every((e) => e.kind && e.kind !== "error" && e.kind !== "no-fetch");
  const firstErr = (p) => (p?.endpoints?.[0] ? `${p.endpoints[0].kind || "?"}: ${p.endpoints[0].detail || ""}` : "?");
  let bitget = persistedBitget || { reachable: false, summary: "not probed", endpoints: [], disclosure: null, probedAt: null };
  let bitgetProbeSource = persistedBitget
    ? `persisted probe ${persistedBitget.probedAt || "n/a"} (data-cache/network-probe.json)`
    : "not probed";
  try {
    log(`probing Bitget endpoints ...`);
    const live = await probeAllBitget({ timeoutMs: Number(cfg.bitget.probeTimeoutMs) });
    if (isClassified(live)) {
      bitget = live;
      bitgetProbeSource = `live probe ${live.probedAt || "n/a"}`;
    } else if (persistedBitget && isClassified(persistedBitget)) {
      bitget = { ...persistedBitget, liveProbeAt: live.probedAt || null, liveProbeUnclassified: firstErr(live) };
      bitgetProbeSource = `persisted probe ${persistedBitget.probedAt || "n/a"} (data-cache/network-probe.json); the live probe at ${live.probedAt || "n/a"} could not classify the failure (${firstErr(live)}) because this run had no direct network egress`;
    } else {
      bitget = live;
      bitgetProbeSource = `live probe ${live.probedAt || "n/a"}`;
    }
  } catch (e) { log(`Bitget probe failed: ${e.message}`); }
  log(`Bitget: ${bitget.summary} [evidence: ${bitgetProbeSource}]`);

  log(`running research task: ${args.symbol} H=${args.horizon} k=${args.k} date=${args.date} stress=${args.stress}`);
  const t1 = Date.now();
  const analysis = desk.analyze({ symbol: args.symbol, date: args.date, horizon: args.horizon, k: args.k, includeStress: args.stress });
  const analyzeMs = Date.now() - t1;
  analysis.card.provenance = {
    ...analysis.card.provenance, ...provenanceBase,
    priceSource: dataset.meta?.sources?.prices || null,
    earningsSource: dataset.meta?.sources?.earningsDates || null,
    bitget,
    bitgetMcp: { status: bitget?.reachable ? "connected" : "degraded", reason: bitget?.reachable ? null : (bitget?.endpoints?.[0] ? `${bitget.endpoints[0].kind}: ${bitget.endpoints[0].detail}` : "not probed") },
    llm: { mode: cfg.llm.enabled ? "LIVE" : "TEMPLATE", model: cfg.llm.model, baseUrl: cfg.llm.baseUrl, keyPresent: cfg.llm.enabled, promptVersion: PROMPT_VERSION }
  };
  log(`analysis done in ${analyzeMs} ms (retrieval ${analysis.detail.timing.retrievalMs} ms); ${analysis.card.distribution?.n ?? 0} analogs, ${analysis.card.stress?.length ?? 0} scenarios`);

  const language = args.language || detectLang(args.question);
  log(`generating narrative (language ${language}, mode ${cfg.llm.enabled ? "LIVE" : "REPLAY/TEMPLATE"}) ...`);
  const narrative = await narrate({ card: analysis.card, question: args.question, language, llm: cfg.llm, store });
  const gate = verifyNumbers(narrative.text, buildAllowlist(analysis.card, defaultAllowance(analysis.card)));
  log(`narrative mode ${narrative.mode}; numeric gate ${gate.ok ? "PASS" : "FAIL"} (${gate.total - gate.unsupportedCount}/${gate.total} numerals traced to the card)`);
  for (const w of narrative.warnings || []) log(`  warning: ${w}`);
  if (!gate.ok) {
    console.error("[demo] FATAL: the narrative cites numbers that are not in the research card. Refusing to publish.");
    console.error(JSON.stringify(gate.unsupported, null, 2));
    process.exit(1);
  }

  const ctx = {
    args, card: analysis.card, narrative, gate, validation: analysis.card.validation, bitget, bitgetProbeSource,
    timing: { engineInitMs, analyzeMs, retrievalMs: analysis.detail.timing.retrievalMs },
    cfg, prov: analysis.card.provenance, task: TASK_NARRATIVE, startedAt, promptVersion: PROMPT_VERSION
  };

  mkdirSync(OUT, { recursive: true });
  const record = {
    schema: "analogdesk.run-record/1",
    generatedAt: startedAt,
    generatedBy: "scripts/run-demo.mjs",
    track: { hackathon: "Bitget AI Base Camp Hackathon S2", track: "Track 3 - AI Trading Desk", subTheme: "Decision Stress Testing" },
    task: { question: args.question, language, symbol: args.symbol, horizon: args.horizon, k: args.k, date: args.date, stressSuite: args.stress, description: TASK_NARRATIVE },
    engine: {
      config: analysis.detail.config,
      library: analysis.detail.library,
      scan: analysis.detail.scan,
      excludedFromDistance: analysis.card.provenance.excludedFromDistance,
      metricFeatureCount: analysis.card.provenance.metricFeatures,
      featureCount: analysis.card.provenance.nFeatures,
      groupWeights: analysis.card.currentState?.groups || []
    },
    narrative: { mode: narrative.mode, model: narrative.model, promptVersion: PROMPT_VERSION, cardId: narrative.cardId,
      latencyMs: narrative.latencyMs ?? null, usage: narrative.usage ?? null, warnings: narrative.warnings || [],
      numericGate: { ok: gate.ok, total: gate.total, unsupportedCount: gate.unsupportedCount, relTol: gate.relTol, structuralPasses: gate.structuralPasses },
      sections: narrative.sections, order: narrative.order, text: narrative.text },
    card: analysis.card,
    detail: analysis.detail,
    validation: analysis.card.validation,
    provenance: analysis.card.provenance,
    bitget,
    bitgetProbeSource,
    timing: { engineInitMs, analyzeMs, retrievalMs: analysis.detail.timing.retrievalMs, totalMs: Date.now() - t0 }
  };
  writeFileSync(join(OUT, "run-record.json"), JSON.stringify(record, null, 2), "utf8");
  const md = `${renderMarkdown(ctx)}\n${renderMarkdownPart2(ctx)}`;
  writeFileSync(join(OUT, "RUN-RECORD.md"), md, "utf8");
  writeFileSync(join(OUT, "narrative.txt"), narrative.text || "", "utf8");

  const kb = (x) => `${(x / 1024).toFixed(1)} KB`;
  log(`wrote demo/run-record.json  ${kb(Buffer.byteLength(JSON.stringify(record, null, 2)))}`);
  log(`wrote demo/RUN-RECORD.md    ${kb(Buffer.byteLength(md))}`);
  log(`wrote demo/narrative.txt    ${kb(Buffer.byteLength(narrative.text || ""))}`);
  log(`headline: ${analysis.card.idea.symbol} ${analysis.card.idea.asOfSession} H=${analysis.card.idea.horizonSessions} - median ${analysis.card.distribution?.medianPct}% , conformal ${analysis.card.conformal?.lowerPct}% .. ${analysis.card.conformal?.upperPct}% (${analysis.card.conformal?.widthPct}% wide), P(loss>10%) ${analysis.card.distribution?.probabilityBelow?.minus10Pct}%, median MAE ${analysis.card.excursion?.maxAdverseMedianPct}%`);
  log(`done.`);
}

main().catch((e) => { console.error("[demo] failed:", e); process.exit(1); });
